repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 20447075e31543a8b125f2df18d75f3b5e7d4d2e  # frozen: 0.22.0
    hooks:
      - id: check-github-actions
        files: .*/action.ya?ml
      - id: check-github-workflows
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 5341f388c2a962d3bc66e075f00b80ab45b15f24 # v0.1.20
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: c9ea83146232fb263effdfe6f222d87f5395b27a # v0.39.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 32ee411cf36142e6082f10870ae62172ce9af133  # frozen: 35.32.0
    hooks:
      - id: renovate-config-validator
