# yamllint disable rule:line-length
---
name: Slack Notifications
on:
  workflow_call:
    inputs:
      slackChannel:
        type: string
        description: Name of the slack channel where the notifications are to be sent.
        default: build
        required: true
      environment:
        required: false
        description: Name of the GitHub Environment to use. Required if your repository uses GitHub Environments with a modified OIDC sub claim. Set to `slack` in this case.
        type: string
        default: ''

jobs:
 slack-notifications:
  runs-on: ubuntu-latest
  name: ${{ github.event.check_run.name }} Slack Notification
  environment: ${{ inputs.environment }}
  permissions:
   id-token: write  # to authenticate via OIDC
  if: >-
      contains(fromJSON('["cirrus-ci", "sonarqube-next", "sonarcloud", "azure-pipelines"]'), github.event.check_run.app.slug)
      && ( contains(fromJSON('["main", "master"]'), github.event.check_run.check_suite.head_branch) || startsWith(github.event.check_run.check_suite.head_branch, 'dogfood-') || startsWith(github.event.check_run.check_suite.head_branch, 'branch-') )
      && github.event.check_run.conclusion != 'success'
      && github.event.check_run.conclusion != 'cancelled'
      && github.event.check_run.conclusion != 'skipped'
      && github.event.check_run.conclusion != 'neutral'
      ||
      (github.event_name == 'check_suite' &&
      contains(fromJSON('["cirrus-ci", "sonarqube-next", "sonarcloud", "azure-pipelines"]'), github.event.check_suite.app.slug)
      && ( contains(fromJSON('["main", "master"]'), github.event.check_suite.head_branch) || startsWith(github.event.check_suite.head_branch, 'dogfood-') || startsWith(github.event.check_suite.head_branch, 'branch-') )
      && github.event.check_suite.conclusion != 'success'
      && github.event.check_suite.conclusion != 'cancelled'
      && github.event.check_suite.conclusion != 'skipped'
      && github.event.check_suite.conclusion != 'neutral')
  steps:
    - name: Vault Secrets
      id: secrets
      uses: SonarSource/vault-action-wrapper@d6d745ffdbc82b040df839b903bc33b5592cd6b0 # 3.0.2
      with:
        secrets: |
          development/kv/data/slack webhook | slack_webhook;
          development/kv/data/slack token | slack_token;

    - name: Get Slack User ID
      id: get-user-id
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      with:
        script: |
          const actor = '${{ github.actor }}';
          const regex = /(\w+)-(\w+)-(\w+)/;
          const matches = actor.match(regex);
          if (matches) {
            const email = `${matches[1]}.${matches[2]}@sonarsource.com`;
            const token = '${{ fromJSON(steps.secrets.outputs.vault).slack_token }}';
            const response = await fetch('https://slack.com/api/users.list', {
              method: 'GET',
              headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
              }
            });
            const data = await response.json();
            if (data.ok) {
              const user = data.members.find(member => member.profile.email === email);
              if (user) {
                core.exportVariable('user_id', user.id);
              } else {
                core.exportVariable('user_id', '');
              }
            } else {
              core.exportVariable('user_id', '');
            }
          } else {
            core.exportVariable('user_id', '');
          }

    - name: Send Slack notification
      uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
      env:
        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.secrets.outputs.vault).slack_webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "channel":"${{ inputs.slackChannel }}",
            "attachments":[
                {
                  "color":"#ee0000",
                  "blocks":[
                      {
                        "type":"section",
                        "text":{
                            "type":"mrkdwn",
                            "text":"*${{ github.event.check_run.app.name }}* - <${{ github.event.check_run.details_url }}|${{ github.event.check_run.name }}> ${{ github.event.check_run.conclusion }}  in *${{ github.repository }}*"
                        }
                      },
                      {
                        "type":"section",
                        "text":{
                            "type":"mrkdwn",
                            "text":"Branch: *${{ github.event.check_run.check_suite.head_branch }}*\nCommit: *${{ github.event.check_run.head_sha }}*\nActor: <@${{ env.user_id }}>"
                        }
                      },
                      {
                        "type": "context",
                        "elements": [
                            {
                              "type": "image",
                              "image_url": "${{ github.event.check_run.app.owner.avatar_url }}",
                              "alt_text": "Icon"
                            },
                            {
                              "type": "mrkdwn",
                              "text": "<${{ github.event.check_run.details_url }}|View more details>"
                            }
                        ]
                      }
                  ]
                }
            ]
          }
